version: 2.1

orbs:
  android: circleci/android@2.4.0

jobs:
  test:
    description: Runs unit tests and instrumented tests on the Android Common
    executor:
      name: android/android-machine
      resource-class: xlarge
      tag: 2024.01.1

    steps:
      - checkout
      - run:
          name: Chmod Permissions
          command: sudo chmod +x gradlew

      - android/create-avd:
          avd-name: avd
          install: true
          system-image: system-images;android-30;google_apis;x86

      - run:
          name: Start ADB server
          command: adb start-server

      - android/start-emulator:
          avd-name: avd
          no-window: true
          restore-gradle-cache-prefix: v1
          memory: 4096
          post-emulator-launch-assemble-command: ./gradlew installSnapshotDebug

      - android/disable-animations

      - run:
          name: Wait for Emulator to be Ready
          command: adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; sleep 5'  # Ensures the emulator is fully booted

      - run:
          name: Restart ADB server
          command: adb kill-server && adb start-server  # Restart ADB server to avoid version mismatch issues

      - run:
          name: Run Instrumented Tests with Retry on Failure
          command: |
            set +e
            for i in {1..2}; do  # Retry up to 2 times
              ./gradlew grantPermissionForODKXApp connectedSnapshotDebugAndroidTest --info
              if [ $? -eq 0 ]; then
                break  # Exit the loop if tests pass
              elif [ $i -eq 2 ]; then
                exit 1  # Exit with failure if tests fail after all retries
              fi
            done

      - run:
          name: Generate JaCoCo Report
          command: ./gradlew jacocoTestReport

      - android/save-gradle-cache:
          cache-prefix: v1

      - store_artifacts:
          name: Store Test Results
          path: services_app/build/outputs/androidTest-results

      - store_artifacts:
          name: Store Test Reports
          path: services_app/build/reports/androidTests/connected

      - store_artifacts:
          name: Store JaCoCo HTML Report
          path: services_app/build/jacocoHtml

  build:
    docker:
      - image: cimg/android:2024.01

    steps:
      - checkout

      - run:
          name: Chmod Permissions
          command: sudo chmod +x gradlew

      - android/restore-gradle-cache:
          cache-prefix: v1

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - android/save-gradle-cache:
          cache-prefix: v1

      - run:
          name: Build Services
          command: ./gradlew assembleSnapshotDebug

      - store_artifacts:
          name: Store Build Artifacts
          path: services_app/build/outputs/apk

      - persist_to_workspace:
          root: .
          paths:
            - services_app/build/outputs/apk

workflows:
  build-test-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
